### Search Product
GET http://localhost:8080/api/products/search?name=육개

### Upload Product
POST http://localhost:8080/api/products/upload?url=https%3A%2F%2Fa.aliexpress.com%2F_olYIyYK
Cookie: JSESSIONID=71835B083B42E879BBED41E3ECEB9150

### Get opend url
GET http://localhost:8080/api/products/opened?productId=14